### ISSUE TITLE
원종화 배안고픔 이슈

### ISSUE THREAD

**Issue by gugyeongmin** [Team-Smeme/Smeme-plan#3]
혼자 점심 늦게 먹고 와서 다같이 저녁 먹으러 가는데 자기 배 안 고프다고 늦게 가자고 함;;
자기만 맛있는 점심 먹고 ;;

- [x] 종화짱이 그럴 리가 없어
- [x] 내일부턴 점심도 같이 먹어ㅡㅡ

@zzongha

**Comment by zzongha** [comment]
ㅋㅋ 내일은 포케 고?
